name = "kleague-odds"
main = "src/index.js"
compatibility_date = "2026-09-01"

[[routes]]
pattern = "kl.usb.kr"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "kleague-odds"
database_id = "b56dde0a-c13e-4119-b69b-ed9ec1054632"
